# Generated by Django 2.1 on 2019-05-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=25)),
                ('receiver', models.CharField(max_length=20)),
                ('detailAddress', models.CharField(max_length=400)),
                ('phoneNum', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=10)),
                ('isUsed', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=25)),
                ('productid', models.CharField(max_length=30)),
                ('productnum', models.IntegerField()),
                ('productprice', models.FloatField()),
                ('isChose', models.BooleanField(default=True)),
                ('productimg', models.CharField(max_length=150)),
                ('productname', models.CharField(max_length=100)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=10)),
                ('typename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=30)),
                ('picUrl', models.CharField(max_length=150)),
                ('picUrlFromIc', models.CharField(max_length=150)),
                ('picUrlM', models.CharField(max_length=150)),
                ('picUrlNew', models.CharField(max_length=150)),
                ('shortName', models.CharField(max_length=50)),
                ('longName', models.CharField(max_length=500)),
                ('specifics', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('categoryid', models.CharField(max_length=10)),
                ('childcid', models.CharField(max_length=10)),
                ('childcidname', models.CharField(max_length=10)),
                ('storenums', models.IntegerField()),
                ('productnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('orderId', models.CharField(max_length=25)),
                ('payWay', models.CharField(max_length=20)),
                ('paymentStatus', models.BooleanField()),
                ('trackNum', models.CharField(max_length=20)),
                ('trackUrl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=25)),
                ('userName', models.CharField(max_length=30)),
                ('passWord', models.CharField(max_length=25)),
                ('mailId', models.CharField(max_length=30)),
                ('phoneNum', models.CharField(max_length=15)),
                ('userAddress', models.CharField(max_length=200)),
                ('userToken', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx.Order'),
        ),
    ]
