# Generated by Django 2.1 on 2019-04-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10)),
                ('picUrl', models.CharField(max_length=150)),
                ('picUrlFromIc', models.CharField(max_length=150)),
                ('picUrlM', models.CharField(max_length=150)),
                ('picUrlNew', models.CharField(max_length=150)),
                ('shortName', models.CharField(max_length=50)),
                ('longName', models.CharField(max_length=100)),
                ('specifics', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('categoryid', models.CharField(max_length=10)),
                ('childcid', models.CharField(max_length=10)),
                ('childcidname', models.CharField(max_length=10)),
                ('storenums', models.IntegerField()),
                ('productnum', models.IntegerField()),
            ],
        ),
    ]
