# Generated by Django 2.1 on 2019-04-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsx', '0004_auto_20190427_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=25)),
                ('userName', models.CharField(max_length=30)),
                ('passWord', models.CharField(max_length=25)),
                ('mailId', models.CharField(max_length=30)),
                ('phoneNum', models.CharField(max_length=15)),
                ('userAddress', models.CharField(max_length=200)),
                ('userToken', models.CharField(max_length=50)),
            ],
        ),
    ]
